# Generated by Django 3.2.16 on 2022-10-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20221021_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='source_links',
            new_name='source_link',
        ),
    ]
